### PR TITLE
CMake improvements

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by chfast** [comment]
@pwnall, can you review this?

**Comment by pwnall** [comment]
@chfast Thank you for the PR!

Could you link to the docs that recommend your approach for the first 2 commits? The last commit adds test coverage, so it's a fairly clear win.

**Comment by chfast** [comment]
> Could you link to the docs that recommend your approach for the first 2 commits?

It's mostly the documentation for `configure_package_config_file()`.
https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#generating-a-package-configuration-file

This is (probably) not needed here, because the config file is very simple and does not need to be generated. But it makes it look like all other package config you can find in many other projects. It also calls `check_required_components()`.

> This macro should be called even if the package doesn’t provide any components to make sure users are not specifying components erroneously.

**Comment by chfast** [comment]
@pwnall ?

**Comment by chfast** [comment]
@pwnall ?

**Comment by chfast** [comment]
Ping.

**Comment by feliwir** [comment]
Any response here @pwnall ?

**Comment by pwnall** [comment]
Sorry for taking so long to review this!

I've landed two of the three commits here, with small changes, credited to chfast.
https://github.com/google/crc32c/commit/ee37bcc11a932f775b32f2e9ea5e78ff6e92839a
https://github.com/google/crc32c/commit/675775b32bc1f11a18b31a5ffd4db2ae471bd16d

I'll still need more time to understand the last commit. Sorry!

**Comment by chfast** [comment]
Oh, great.

The third commit follows CMake recommendation how to create CMake package configs. For this project this might not be needed as there are no dependencies.

If you want, I can rebase this PR and investigate if there is any difference.

**Comment by pwnall** [comment]
@chfast Could you see if you're ok with the changes in https://github.com/google/crc32c/tree/chfast-cmake-3 ?

I've looked around for examples, and I'd like to use that variation. If you prefer to see the merged sign here, you can rebase+update this PR. Otherwise, I can land that commit and close this PR.

**Comment by chfast** [comment]
Looks great, thanks!

**Comment by pwnall** [comment]
All commits here have been landed. Thank you very much for your contributions!

**Pull request closed without merging**
