### PR TITLE
Add shared library mode to Travis CI.

### PR DESCRIPTION
**Pull request by pwnall**
This adds some CI coverage for shared library builds, and includes some cosmetic cleanups.

### CODE REVIEW

**Comment by pwnall** [comment]
@cmumford PTAL?

**Comment by cmumford** [comment]
Do you want a configuration with GLOG=1 SHARED_LIB=1, or was that intentionally omitted?

**Comment by pwnall** [comment]
Intentionally omitted. I am adding coverage because customers are using shared libraries, and this only happens with our recommended flags GLOG=0.

**Comment by pwnall** [comment]
@cmumford Thank you very much for the quick review!

**Pull request merged**
