### PR TITLE
Bump third-party dependencies and fix MSVC compile warning

### PR DESCRIPTION
**Pull request by pwnall**

### CODE REVIEW

**Comment by pwnall** [comment]
@cmumford  PTAL?

**Comment by cmumford** [comment]
Do you know what the source of the travic-ci error is? Error: Failed to download resource "gcc"

**Comment by pwnall** [comment]
@cmumford Travis flake. I restarted the build and it passed.

**Comment by pwnall** [comment]
@cmumford Thank you very much for the quick review!

**Pull request merged**
